symbolsPerLine: 30
# If the limit is reached, the three dots will be added at the end. -1 means there's no limit
symbolsLimit: -1
# Initial amount of seconds for the message to exist
timeToExist: 2
# Whether a message will be visible to the sender
visibleToSender: true

# Whether a longer message will exist for more time
scalingEnabled: true
# Scaling coefficient per symbol in seconds. For example, a message with 50 symbols
# will exist for extra 5 seconds if the coefficient is set to 0.1 (because 0.1 * 50 = 5)
scalingCoefficient: 0.05

# Distances between messages / above player's head
gapBetweenMessages: 0.3
gapAboveHead: 0.4

textColor: "#FFFFFF"

timerEnabled: true
# Minimum message length threshold for the timer to be displayed
minSymbolsForTimer: 0
timerFormat: " (%.1f)"
timerColor: "#F4CA16"

backgroundEnabled: true
backgroundColor: "#000000"
# Range: [0, 100]
backgroundTransparencyPercentage: 100

# Whether a text will have a shadow
isShadowed: true

# How a text display can pivot:
# VERTICAL - Can pivot around vertical axis
# HORIZONTAL - Can pivot around horizontal axis
# CENTER - Can pivot around center point
# FIXED - No rotation
pivotAxis: "VERTICAL"

# You may enable this if you use a plugin for per-player chat color customization (e.g., EZColors, ChatColor etc.)
placeholderApiIntegration: false
# Name of a placeholder that will be put before each text line
colorPlaceholder: "%ezcolors_color%"
# Format for text lines if `placeholderApiIntegration` is true
lineFormat: "&[defaultColor]&[colorPlaceholder][message]"

messages:
  "prefix": "&#F4CA16[MessagesOnHead]"
  "info-content": "<prefix> &#D9E6EDCommands list:
  \n &f/moh reload - &#D9E6EDReloads the config and makes a cleanup by removing all entities related to the plugin.
  \n &f/moh say - &#D9E6EDSay a message on behalf of the player."
  "reloaded": "<prefix> &#D9E6EDReloaded!"
  "player-not-found": "<prefix> Player not found."
  "command-not-found": "<prefix> &cCommand not found."
  "error-during-reload": "<prefix> &cAn error occurred during reload! Check console for details."