name: MessagesOnHead
version: '${project.version}'
main: mrquackduck.messagesonhead.MessagesOnHeadPlugin
api-version: '1.19'

commands:
  messagesonhead:
    description: The MessagesOnHead command
    permission: messagesonhead.admin
    aliases:
      - moh

permissions:
  messagesonhead.show:
    description: Whether messages will appear above player's head
    default: true
  messagesonhead.admin:
    description: Allows to use staff commands of the plugin
    default: op

softdepend: [PlaceholderAPI]